### ISSUE TITLE
返回类型问题

### ISSUE THREAD

**Issue by FelixFu520** [huangfeidian/entity_component_factory#5]
我在运行[factory_test.cpp](https://github.com/huangfeidian/entity_component_factory/blob/main/test/factory_test.cpp)时，将Dog类增加了一个makeNoise(int a)方法，但是我在

```
auto x = AnimalFactory::make_by_name("Dog", 3);
x->makeNoise(1);
```
报错，编译不过去， x是Dog类的共享指针, 为什么我访问不到makeNoise(int a)方法，如何才能访问到？

**Comment by FelixFu520** [comment]
x是动态运行时，才确定时Dog类型，有没有方法改成编译时就知道x是Dog类型，这样我才能从工厂中拿到自己想要的类

**Comment by huangfeidian** [comment]
工厂的意思就是构造出基类给你，如果你知道所需类型，直接new Dog(3)不就行了？ 从基类转换到子类你可以用dynamic_cast<Dog*>(x)
